[bar]
scale = 0.800000011920929
padding = 0.10000000149011612
button-variant = "basic"
button-icon-padding = 0.25

[[bar.layout]]
monitor = "eDP-1"
show = true
left = [
    "dashboard",
    "hyprland-workspaces",
]
center = ["clock"]
right = [
    "media",
    "systray",
    "cpu",
    "ram",
    "bluetooth",
    "network",
    "volume",
    "battery",
]

[[bar.layout]]
monitor = "*"
show = false
left = ["media"]
center = ["clock"]
right = [
    "battery",
    "bluetooth",
    "network",
    "microphone",
    "volume",
]

[styling]
theme-provider = "matugen"

[modules.bluetooth]
label-show = false

[modules.clock]
format = "%a %-d %b - %R"

[modules.hyprland-workspaces]
min-workspace-count = 9
monitor-specific = false
show-special = false
app-icons-show = true

[modules.hyprland-workspaces.workspace-map.1]
label = "一"

[modules.hyprland-workspaces.workspace-map.10]
label = "十"

[modules.hyprland-workspaces.workspace-map.2]
label = "二"

[modules.hyprland-workspaces.workspace-map.3]
label = "三"

[modules.hyprland-workspaces.workspace-map.4]
label = "四"

[modules.hyprland-workspaces.workspace-map.5]
label = "五"

[modules.hyprland-workspaces.workspace-map.6]
label = "六"

[modules.hyprland-workspaces.workspace-map.7]
label = "七"

[modules.hyprland-workspaces.workspace-map.8]
label = "八"

[modules.hyprland-workspaces.workspace-map.9]
label = "九"

[wallpaper]
transition-type = "none"
transition-duration = 0.0
