[bar]
scale = 0.800000011920929
padding = 0.10000000149011612
button-variant = "basic"
button-icon-padding = 0.25

[[bar.layout]]
monitor = "eDP-1"
show = true
left = [
    "dashboard",
    "hyprland-workspaces",
]
center = ["clock"]
right = [
    "media",
    "systray",
    "cpu",
    "ram",
    "bluetooth",
    "network",
    "volume",
    "battery",
]

[[bar.layout]]
monitor = "*"
show = false
left = ["media"]
center = ["clock"]
right = [
    "battery",
    "bluetooth",
    "network",
    "microphone",
    "volume",
]

[styling]
theme-provider = "matugen"

[modules.bluetooth]
label-show = false

[modules.clock]
format = "%a %-d %b - %R"

[modules.hyprland-workspaces]
monitor-specific = false
show-special = false
app-icons-show = true

[wallpaper]
transition-type = "none"
transition-duration = 0.0
